name: benchmark
description: Benchmark, not for publishing.
version: 0.0.1

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.9.0-18.0 <3.0.0'

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any

dependency_overrides:
  built_collection:
    path: ..
